# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 008e69e3a8ca84a4fab7b9b829d227647a6d455f05a65324f680bfca7302ef35a52d0a2eb982ff180f7f8bd387cdcd6c0df19bb2397a1f3438b6de25aa90025e

test:
  secret_key_base: 6686b6418369781ac8a744212ac8dca419d64742ac842e0498d6489e556486c3fe086ff378ac7788f7baa18411cceebb77c2a15b7ff0e36f7d0aa96e34e7d8a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
